### ISSUE TITLE
Newest version of evno crashes with a type error

### ISSUE THREAD

**Issue by phochste** [ErfgoedPod/evno#8]
When trying to read my own inbox I get an error

```
TypeError: body used already for: https://patrickhochstenbach.net/inbox/85d79e02-1c8a-43b6-8302-a41f2a380a46
```

This line

https://github.com/ErfgoedPod/evno/blob/main/src/receiver.ts#L149

and this line

https://github.com/ErfgoedPod/evno/blob/main/src/receiver.ts#L154

clash when polling data from the inbox because two times we try to read the text content from an HTTP response.

**Comment by mielvds** [comment]
Fixed in d6034c0a6be83e512cb53799cfea71cf1af3886f
